title: Business Analytics & Data Science Projects
logo: /assets/Headshot.png
#description text below logo
show_download: false
theme: jekyll-theme-minimal

description: Ahad Mohamed

#External navigation links
nav_links:
  - title: "MIP Optimizer"
    url: "https://am-msba.github.io/MIP-Optimization-Solver/"
  - title: "ML Prediction Model"
    url: "https://am-msba.github.io/Machine_Learning_Prediction_Project/"
